version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./volumes/var/ha/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    ports:
      - 8123:8123  # HA 控台的 port
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    volumes:
      - ./volumes/opt/mosquitto:/mosquitto
    ports:
      - 1883:1883
      - 9001:9001
  # 如果要把 zigbee2mqtt 整合在同一台機器上...
#  zigbee2mqtt:
#    container_name: zigbee2mqtt
#    depends_on:
#      - mosquitto
#    image: koenkk/zigbee2mqtt
#    volumes:
#      - ./volumes/zigbee2mqtt/data:/app/data
#      - /run/udev:/run/udev:ro
#    ports:
#      - 8080:8080
#    devices:
#      - /dev/ttyUSB0:/dev/ttyUSB0
#    restart: always
#    privileged: true