version: "3"
services:
  portainer:
    image: portainer/portainer-ce
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - mynetwork
#    ports:
#      - 9000:9000
    container_name: portainer

volumes:
  portainer_data: 

networks:
  mynetwork:
    external: true
