version: '3'
services:
  web:
    image: nginx
    volumes:
      # - ./templates:/etc/nginx/templates
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - mynetwork
        ipv4_address: 172.22.0.4
    ports:
     - "80:80"
     - "443:443"
    environment:
     - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.conf
     - NGINX_PORT=80

networks:
  mynetwork:
    external: true
